### ISSUE TITLE
7z file compressed by mcmilk 7zip R6 cannot be decompressed by p7zip 

### ISSUE THREAD

**Issue by moreffort** [tehmul/p7zip-zstd#1]
Hi,

Error log likes:
ERROR: Data Error : zstdtest/README
ERROR: Data Error : zstdtest/TODO
ERROR: Data Error : zstdtest/Utils/bin_to_sources.py
ERROR: Data Error : zstdtest/Utils/CPUTest/Benchmark.h
ERROR: Data Error : zstdtest/Utils/CPUTest/MemLat/makefile
ERROR: Data Error : zstdtest/Utils/CPUTest/MemLat/makefile.list
ERROR: Data Error : zstdtest/Utils/CPUTest/MemLat/MemLat.cpp
ERROR: Data Error : zstdtest/Utils/CPUTest/MemLat/Walk.c
ERROR: Data Error : zstdtest/Utils/CPUTest/MemLat/Walk.h
ERROR: Data Error : zstdtest/Utils/CPUTest/MemLat/Walk32.asm
ERROR: Data Error : zstdtest/Utils/CPUTest/MemLat/Walk64.asm
ERROR: Data Error : zstdtest/Utils/CPUTest/MyVersion.h
ERROR: Data Error : zstdtest/Utils/CPUTest/PipeLen/makefile
ERROR: Data Error : zstdtest/Utils/CPUTest/PipeLen/makefile.list
ERROR: Data Error : zstdtest/Utils/CPUTest/PipeLen/MemLat
ERROR: Data Error : zstdtest/Utils/CPUTest/PipeLen/PipeLen.cpp
ERROR: Data Error : zstdtest/Utils/CPUTest/PipeLen/pl32.asm
ERROR: Data Error : zstdtest/Utils/file_7z.py
ERROR: Data Error : zstdtest/Utils/file_7za.py
ERROR: Data Error : zstdtest/Utils/file_7zCon_sfx.py
ERROR: Data Error : zstdtest/Utils/file_7zFM.py
ERROR: Data Error : zstdtest/Utils/file_7zG.py
ERROR: Data Error : zstdtest/Utils/file_7zr.py
ERROR: Data Error : zstdtest/Utils/file_7z_so.py
ERROR: Data Error : zstdtest/Utils/file_Client7z.py
ERROR: Data Error : zstdtest/Utils/file_Codecs_Lzham_so.py
ERROR: Data Error : zstdtest/Utils/file_Codecs_Rar_so.py
ERROR: Data Error : zstdtest/Utils/file_Codecs_ZStd_so.py

The  mcmilk 7zip R5 is OK. According to  mcmilk's explanation, it seems that p7zip doesn't support skipable frames.

**Comment by ghost** [comment]
@tehmul - Take a look into the st_decompress() function of [zstdmt_decompress.c](https://github.com/mcmilk/zstdmt/blob/dev/lib/zstdmt_decompress.c) ... this one should decompress skipable frames properly and is single threaded... I am very busy in the moment, so I can not provide some patch currently...

**Comment by tehmul** [comment]
@moreffort - try building the develop branch and running 7za (not 7z) and see?
@mcmilk  - Thanks!

**Comment by moreffort** [comment]
@tehmul , We failed to build the develop branch. There are some errors like:

g++ -c -I. -I../../../../C -I../../../../C/zstd -I../../../../C/zstdmt -I../../../../CPP/myWindows -I../../../../CPP/include_windows -I../../../../CPP -O -s -pipe -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -DNDEBUG -D_REENTRANT -DENV_UNIX -D_7ZIP_LARGE_PAGES  -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_REENTRANT -DENV_UNIX -DBREAK_HANDLER -DUNICODE -D_UNICODE -DUNIX_USE_WIN_FILE   ../../../../CPP/7zip/Archive/ZstdHandler.cpp
In file included from ../../../../CPP/7zip/Archive/../Compress/ZstdDecoder.h:12,
                 from ../../../../CPP/7zip/Archive/ZstdHandler.cpp:13:
../../../../CPP/7zip/Archive/../Compress/../../../C/zstdmt/zstdmt.h:81: error: declaration of ‘int (* <anonymous struct>::fn_read)(void*, ZSTDMT_Buffer*)’
../../../../CPP/7zip/Archive/../Compress/../../../C/zstdmt/zstdmt.h:77: error: changes meaning of ‘fn_read’ from ‘typedef int fn_read(void*, struct ZSTDMT_Buffer*)’
../../../../CPP/7zip/Archive/../Compress/../../../C/zstdmt/zstdmt.h:83: error: declaration of ‘int (* <anonymous struct>::fn_write)(void*, ZSTDMT_Buffer*)’
../../../../CPP/7zip/Archive/../Compress/../../../C/zstdmt/zstdmt.h:78: error: changes meaning of ‘fn_write’ from ‘typedef int fn_write(void*, struct ZSTDMT_Buffer*)’
make[1]: *** [ZstdHandler.o] Error 1

Thanks!

**Comment by tehmul** [comment]
What gcc version are you using? Also what environment - Linux/cygwin/mingw?

I've commited a few more changes to the develop branch and now 7z does seem to work.

I did a fresh git clone followed by 
```
git checkout develop
cd p7zip_16.02
make all3 all4 
bin/7z t test.zs ## test.zs was created with mcmilk 7zip R6 
```
(I tested with gcc 6.2 on openSUSE and gcc4.8.2 on RedHat EL 7)

**Comment by moreffort** [comment]
It works now after I upgraded gcc to gcc version 4.7.2 20121015 (Red Hat 4.7.2-5) (GCC). 
Thanks very much!

**Comment by tehmul** [comment]
Cool :)
